name: Build
on: [pull_request, push]
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run ktlint
        run: ./gradlew ktlint

      - name: Run detekt
        run: ./gradlew detekt

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

#  ui-test:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Run UI tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          arch: 'x86_64'
#          api-level: 30
#          script: ./gradlew connectedDebugAndroidTest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew assembleDebug
